name = "strainchain-io"
main = "src/index.ts"
compatibility_date = "2026-04-01"
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = false

[[routes]]
pattern = "strainchain.io/*"
zone_name = "strainchain.io"

[[routes]]
pattern = "www.strainchain.io/*"
zone_name = "strainchain.io"



