/**
 * seo-data/comparison.cjs
 * DATA entries for gen-seo-pages.cjs: "alternative to X" and plan-pricing
 * pages built from the plan catalogue (src/lib/plans.ts) and the vetted
 * /vs comparison copy (workers/authichain-com/src/vs-pages*.ts).
 *
 * Rules for this file (the weekly marketing-pages routine appends here):
 * - Prices and plan names come from src/lib/plans.ts listed plans only. Never
 *   name a plan that is listed: false or absent from PUBLIC_PLAN_IDS.
 * - A competitor claim must already appear in vs-pages*.ts or be checked
 *   against the competitor's own site the week it is written. If it can't be
 *   checked, leave it out rather than guess.
 * - AuthiChain capabilities keep the same status the /vs pages give them:
 *   "in development" stays in development, "goal" stays a goal.
 * Shape must match gen-seo-pages.cjs's DATA entries exactly: keyword, brand,
 * schemaType, lead, bullets[3], faqs[{q,a}]. Required by gen-seo-pages.cjs.
 */
module.exports = [
  { keyword: 'vechain alternative without tokens or gas fees', brand: 'authichain', schemaType: 'Service',
    lead: 'VeChain is a general-purpose enterprise L1 blockchain that brands usually reach through ToolChain or an integration partner; AuthiChain is a brand-facing product instead, where the seal, the certificate and the public verifier are the thing you buy, and you pay in USD by card rather than holding a token.',
    bullets: ['No token and no gas to manage: AuthiChain plans are billed in US dollars through Stripe, so a brand never has to fund a wallet before it can issue a record', 'Signing keys are published at /.well-known/jwks.json. Product certification through verify is in development.', 'Self-serve issuance and EU DPP export are still in development. The $299 checkout is a one-time payment; it is not a readiness audit.'],
    faqs: [{ q: 'Is AuthiChain built on VeChain?', a: 'No. VeChain is a separate L1 blockchain that other authentication vendors build on.' }, { q: 'What does it cost to start?', a: 'The live entry point is the EU DPP Readiness checkout at $299. Stripe confirms payment and links to a short onboarding form.' }] },
  { keyword: 'circularise alternative for smaller brands', brand: 'authichain', schemaType: 'Service',
    lead: 'Circularise is an enterprise platform for material traceability and EU Digital Product Passports aimed at large manufacturers on quoted contracts; a smaller brand that needs to start its DPP work without an enterprise sales cycle can begin with AuthiChain’s $299 EU DPP Readiness checkout, paid by card.',
    bullets: ['The $299 checkout is a one-time payment; stripe confirms payment and links to a short onboarding form', 'AuthiChain covers anti-counterfeit authentication as well as DPP readiness, while Circularise specializes in material traceability for large supply chains', 'EU DPP export is still in development at AuthiChain; if you need a production passport export for a delegated act deadline today, weigh that honestly against a platform that already ships one'],
    faqs: [{ q: 'Does AuthiChain export an EU Digital Product Passport today?', a: 'Not yet. DPP export is in development. The $299 checkout is a one-time payment. Stripe confirms payment and links to a short onboarding form.' }, { q: 'Is the $299 wasted if we later need more?', a: 'The $299 checkout is a one-time payment. Stripe confirms payment and links to a short onboarding form.' }] },
  { keyword: 'scantrust alternative with a public verifier', brand: 'authichain', schemaType: 'Product',
    lead: 'Scantrust is an established secure-QR and brand-protection platform with self-serve plans; the difference AuthiChain leads with is a record anyone can check against published keys, so a buyer, customs officer or marketplace can verify a signed claim without asking the brand or AuthiChain.',
    bullets: ['Signing keys are published at /api/v1/.well-known/jwks.json and the verification rules are open, so the check does not depend on AuthiChain staying online or on a vendor account', 'A valid signature is signed evidence of what the issuer recorded, not a guarantee that the object in hand is genuine; the page says so rather than implying more'],
    faqs: [{ q: 'Can a customer verify without an app?', a: 'Yes. Scanning the code opens the public verifier in a normal browser, and offline signature checks against the published JWKS are in development.' }, { q: 'Does AuthiChain use secure copy-detection QR codes like Scantrust?', a: 'No. AuthiChain’s approach is a signed record behind the code (signing is in development) rather than a print pattern, so the two approaches answer different questions and can be used together.' }] },
  { keyword: 'cannabis coa passport pricing per cultivar', brand: 'strainchain', schemaType: 'Product',
    meta: 'A StrainChain genetics passport costs $49 per cultivar as a one-time payment. Farm is not a public offer.',
    lead: 'A StrainChain genetics passport costs $49 per cultivar as a one-time payment. Farm is not a public offer.',
    bullets: ['Passport, $49 once: one published passport for one cultivar, with the full cannabinoid and terpene panel taken from your existing certificates and a QR code and shareable link', 'On the passport every THC and THCV total is recomputed from the raw panel rather than copied from the certificate, and discrepancies are shown rather than smoothed over'],
    faqs: [{ q: 'Is a StrainChain passport a lab result?', a: 'No. It is a published record built from the certificates you supply. The lab that issued the CoA remains the source of the test result.' }, { q: 'Is Farm a public offer?', a: 'No. The public StrainChain offer is the $49 genetics passport. Farm stays off the public catalogue.' }] },
  { keyword: 'uk battery exporter eu battery passport', brand: 'authichain', schemaType: 'Service',
    lead: 'A UK maker selling e-bike, e-scooter, industrial or EV batteries into the EU still needs an EU battery passport from 18 February 2027 under Article 77 of Regulation (EU) 2023/1542, because the rule follows the battery onto the EU market, not the factory it came from.',
    bullets: ['The passport duty sits with the economic operator that places the battery on the EU market, which for a UK exporter is usually the EU importer or distributor, so expect them to ask you for the Annex XIII data rather than build it themselves', 'It covers LMT batteries, industrial batteries above 2 kWh and EV batteries, each needing a unique identifier and a QR code on the battery that opens its passport record', 'The battery page runs a free figure check and an Annex XIII gap table on the figures you type, so you can see which fields still need an owner before an EU buyer asks'],
    faqs: [{ q: 'Does UK law require a battery passport?', a: 'This page covers the EU requirement only. Great Britain has its own battery rules; what matters for EU sales is Regulation (EU) 2023/1542, which applies to every battery placed on the EU market.' }, { q: 'What can I see before I pay?', a: 'A full sample, worked through on a fictional 48 V e-bike pack, is at https://authichain.com/battery-passport/sample-audit. The $299 checkout confirms payment and links to a short onboarding form; it is not an assessment.' }] },
  { keyword: 'us battery manufacturer eu battery passport export', brand: 'authichain', schemaType: 'Service',
    lead: 'US battery and e-mobility manufacturers exporting to the EU face the same 18 February 2027 battery passport deadline as European makers, because Article 77 of Regulation (EU) 2023/1542 applies to LMT, industrial above 2 kWh and EV batteries placed on the EU market, wherever they were built.',
    bullets: ['Your EU importer or distributor carries the legal duty to make the passport available, but most of the Annex XIII data, from chemistry and capacity to supply-chain details, only the manufacturer can provide', 'Each battery needs a unique identifier and a QR code that resolves to its passport, with some fields public and others limited to interested parties and authorities', 'Checking the datasheet figures and field ownership now leaves time to fix gaps before an EU buyer makes the passport a condition of the next purchase order'],
    faqs: [{ q: 'We do not sell in Europe directly. Does this still affect us?', a: 'If your batteries reach the EU through a distributor or inside a product such as an e-bike, the operator placing them on the EU market needs the passport, and they will need your data to produce it.' }, { q: 'Where do we start?', a: 'Read the fictional walkthrough at https://authichain.com/battery-passport/sample-audit. The $299 checkout is a one-time payment. Stripe confirms payment and links to a short onboarding form.' }] },
  { keyword: 'battery passport readiness assessment cost', brand: 'authichain', schemaType: 'Product',
    lead: 'AuthiChain’s EU DPP Readiness checkout is $299 one-time. Stripe confirms payment and links to a short onboarding form. A fictional e-bike walkthrough of the free figure check and Annex XIII gap table is at https://authichain.com/battery-passport/sample-audit. That page is not a document the checkout sends.',
    bullets: ['You can read a fictional walkthrough first at https://authichain.com/battery-passport/sample-audit, worked through on a fictional 48 V e-bike pack, including a datasheet figure check and the gap table', 'The purchase is a one-time payment; stripe confirms payment and links to a short onboarding form', 'The checkout is not an assessment. It is not a certification or legal opinion, and EU DPP export from AuthiChain is still in development'],
    faqs: [{ q: 'Is the $299 a subscription?', a: 'No. It is a single payment through Stripe with no recurring charge.' }] },
];
