/**
 * @file seo-pages.ts
 * Loader for committed programmatic-SEO pages (content/seo/pages.json).
 * Generated by the SEO agent and committed so pages render statically/ISR with
 * no runtime LLM or DB dependency. The /p/[slug] route + sitemap read from here.
 *
 * Pages published by server/agents/seo-content.ts's daily cron batch land in
 * the seo_pages DB table instead (no rebuild needed for a new page to go
 * live, since /p/[slug] is already force-dynamic) — the *WithDb variants
 * below merge both sources. The plain functions stay static-only and
 * synchronous so existing callers/tests are unaffected.
 */
import { eq } from 'drizzle-orm';
import pagesData from '../../content/seo/pages.json';
import { seoPages } from '../../drizzle/schema';
import type { getDb } from '../../server/db';

export interface SeoPage {
  slug: string;
  keyword: string;
  brand: string;
  domain: string;
  title: string;
  metaDescription: string;
  h1: string;
  bodyHtml: string;
  jsonLd: Record<string, unknown>;
}

type Db = Awaited<ReturnType<typeof getDb>>;

const ALL: SeoPage[] = pagesData as unknown as SeoPage[];

export function listSeoPages(): SeoPage[] {
  return ALL;
}

export function listSeoSlugs(): string[] {
  return ALL.map((p) => p.slug);
}

export function getSeoPageBySlug(slug: string): SeoPage | null {
  return ALL.find((p) => p.slug === slug) ?? null;
}

export async function listSeoPagesWithDb(db: Db): Promise<SeoPage[]> {
  const rows = await db.select().from(seoPages);
  return [...ALL, ...rows.map(rowToSeoPage)];
}

export async function getSeoPageBySlugWithDb(slug: string, db: Db): Promise<SeoPage | null> {
  const staticPage = getSeoPageBySlug(slug);
  if (staticPage) return staticPage;
  const [row] = await db.select().from(seoPages).where(eq(seoPages.slug, slug)).limit(1);
  return row ? rowToSeoPage(row) : null;
}

function rowToSeoPage(row: typeof seoPages.$inferSelect): SeoPage {
  return {
    slug: row.slug,
    keyword: row.keyword,
    brand: row.brand,
    domain: row.domain,
    title: row.title,
    metaDescription: row.metaDescription,
    h1: row.h1,
    bodyHtml: row.bodyHtml,
    jsonLd: row.jsonLd as Record<string, unknown>,
  };
}
