/**
 * @file seo-pages.ts
 * Loader for committed programmatic-SEO pages (content/seo/pages.json).
 * Generated by the SEO agent and committed so pages render statically/ISR with
 * no runtime LLM or DB dependency. The /p/[slug] route + sitemap read from here.
 */
import pagesData from '../../content/seo/pages.json';

export interface SeoPage {
  slug: string;
  keyword: string;
  brand: string;
  domain: string;
  title: string;
  metaDescription: string;
  h1: string;
  bodyHtml: string;
  jsonLd: Record<string, unknown>;
}

const ALL: SeoPage[] = pagesData as unknown as SeoPage[];

export function listSeoPages(): SeoPage[] {
  return ALL;
}

export function listSeoSlugs(): string[] {
  return ALL.map((p) => p.slug);
}

export function getSeoPageBySlug(slug: string): SeoPage | null {
  return ALL.find((p) => p.slug === slug) ?? null;
}
