export const MISSION_TYPES = [
  'GOV_PILOT',
  'RETAIL_PILOT',
  'PRESS_LAUNCH',
  'PARTNER_ONBOARDING',
  'TECH_OS_LOCK',
  'LAUNCH_AUTHICHAIN',
  'LUXURY_OUTREACH',
  'PHARMA_OUTREACH',
  'MEDTECH_OUTREACH',
  'TIMEPIECE_OUTREACH',
  'NEWSJACKING_LAUNCH',
  'TECH_SPRINT',
  'MEDTECH_VIDEO_BRIEFING',
  'MI_CRA_PARTNERSHIP',
] as const;

export type MissionType = typeof MISSION_TYPES[number];

export const MISSION_STATUSES = ['PLANNED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED'] as const;

export type MissionStatus = typeof MISSION_STATUSES[number];

export type TaskStatus = 'PENDING' | 'RUNNING' | 'WAITING_HUMAN' | 'DONE' | 'FAILED';

export type TaskKind =
  | 'FIND_GOV_LEADS'
  | 'FIND_RETAIL_LEADS'
  | 'FIND_LUXURY_LEADS'
  | 'FIND_PHARMA_LEADS'
  | 'FIND_MEDTECH_LEADS'
  | 'FIND_TIMEPIECE_LEADS'
  | 'MONITOR_NEWS_FOR_PR'
  | 'DRAFT_OUTBOUND_EMAIL'
  | 'BUILD_PILOT_PACKET'
  | 'DRAFT_INTEL_DOSSIER'
  | 'FOLLOWUP_SEQUENCE'
  | 'CRM_UPDATE'
  | 'FINALIZE_RETAIL_SIGNAGE'
  | 'PACKAGE_SKU_ONBOARDING'
  | 'CHECK_DNS_CONFIG'
  | 'VERIFY_SSL'
  | 'RUN_LIGHTHOUSE_AUDIT'
  | 'GENERATE_LAUNCH_CHECKLIST'
  | 'DRAFT_LAUNCH_EMAIL'
  | 'DRAFT_PRESS_RELEASE'
  | 'SCHEDULE_SOCIAL_POSTS'
  | 'CHECK_REPLIES'
  | 'SEND_DEMO_PACKET'
  | 'GENERATE_PROPOSAL'
  | 'SEND_CONTRACT'
  | 'AUTO_REPLY'
  | 'GENERATE_OUTREACH_VIDEO'
  | 'SECURITY_AUDIT'
  // ── Dev Team ──────────────────────────────────────────────
  | 'PLAN_SPRINT'
  | 'WRITE_CODE'
  | 'OPEN_PR'
  | 'RUN_TESTS'
  | 'CODE_REVIEW'
  | 'MERGE_PR'
  | 'MONITOR_DEPLOY'
  | 'FILE_BUG'
  | 'AUTO_FIX';

export type LeadSegment = 'GOV' | 'RETAIL' | 'PRESS';

export type LeadStatus =
  | 'NEW'
  | 'CONTACTED'
  | 'REPLIED'
  | 'MEETING_SCHEDULED'
  | 'PILOT_PROPOSED'
  | 'CLOSED_WON'
  | 'CLOSED_LOST';
