// Wrangler entry for authichain-app (wrangler.app.jsonc → "main").
//
// The live authichain-app script already owns a SQLite-backed Durable Object
// namespace for class RateLimiter (created by migration tag "v1"). Cloudflare
// rejects any new version that stops exporting a class existing Durable
// Objects depend on (API error 10064), so the plain OpenNext worker
// (.open-next/worker.js), which does not export RateLimiter, cannot deploy.
//
// This thin wrapper keeps the OpenNext worker as the default export, re-exports
// OpenNext's own Durable Object classes, and adds RateLimiter from its source
// of truth in worker-app/rate-limiter.ts. Never "fix" 10064 with a
// delete-class migration: that wipes the namespace's data.
//
// .open-next/worker.js is generated by `opennextjs-cloudflare build`; wrangler
// bundles this file (and that output) with esbuild at deploy time.

// @ts-ignore -- generated at build time, no type declarations
export * from "./.open-next/worker.js";
// @ts-ignore -- generated at build time, no type declarations
export { default } from "./.open-next/worker.js";
export { RateLimiter } from "./worker-app/rate-limiter";
