import { CalendarClock, CheckCircle2, ExternalLink, Search, ShieldCheck, Sparkles, WalletCards } from 'lucide-react';

type Claim = { name:string; category:string; score:number; proof:string; deadline:string; value:string; status:string; source:string };

const claims: Claim[] = [
  {name:'Privacy & Data Settlement',category:'Privacy',score:97,proof:'No documentation',deadline:'14 days',value:'$25–$85',status:'Ready to review',source:'Official administrator'},
  {name:'Consumer Subscription Settlement',category:'Consumer',score:93,proof:'No documentation',deadline:'23 days',value:'$15–$60',status:'Ready to review',source:'Official administrator'},
  {name:'Payment Processing Settlement',category:'Payments',score:88,proof:'Low',deadline:'41 days',value:'$40–$180',status:'Needs one fact',source:'Court notice + administrator'},
  {name:'Product Warranty Settlement',category:'Products',score:74,proof:'Receipt may help',deadline:'67 days',value:'$50–$250',status:'Needs review',source:'Court notice'},
];

function Score({score}:{score:number}){return <span className={score>=90?'good':score>=70?'warn':'bad'}>{score}%</span>}

export default function ClaimPilotPage(){
  const total = claims.reduce((n,c)=>n+Number(c.value.split('–')[0].replace(/\D/g,'')),0);
  return <main className="shell">
    <header className="topbar"><div className="brand"><div className="mark">CP</div><div><h1>ClaimPilot</h1><div className="muted">Personal claims recovery OS</div></div></div><div className="pill"><ShieldCheck size={13} style={{verticalAlign:'-2px'}}/> Evidence-first mode</div></header>
    <section className="hero"><div className="card"><div className="pill" style={{display:'inline-block',marginBottom:12}}><Sparkles size={13} style={{verticalAlign:'-2px'}}/> Discovery engine</div><h2>Find money you can legitimately claim.</h2><p>ClaimPilot continuously discovers settlements, verifies official sources, matches eligibility rules, separates no-proof claims from documented claims, and keeps every deadline in one place.</p><div className="filters"><button className="button primary"><Search size={14} style={{verticalAlign:'-2px'}}/> Scan for new claims</button><button className="button">No proof only</button><button className="button">High confidence</button></div></div><div className="card"><div className="muted">Estimated opportunity floor</div><div className="hero h2" style={{fontSize:30,marginTop:10}}>${total}+</div><div className="notice">Estimates are informational, not guaranteed payouts. ClaimPilot never invents qualifying facts or evidence.</div></div></section>
    <section className="kpis"><div className="card kpi"><div className="label">Open matches</div><div className="value">17</div></div><div className="card kpi"><div className="label">No-proof matches</div><div className="value good">9</div></div><div className="card kpi"><div className="label">Ready to review</div><div className="value">6</div></div><div className="card kpi"><div className="label">Deadlines ≤ 14d</div><div className="value warn">3</div></div></section>
    <div className="grid"><section className="card"><div className="section-head"><h3>Claim queue</h3><span className="muted">Sorted by expected value / effort</span></div>{claims.map((c)=><article className="claim" key={c.name}><div><h4>{c.name}</h4><div className="meta"><span className="pill">{c.category}</span><span className="pill">{c.proof}</span><span className="deadline"><CalendarClock size={13} style={{verticalAlign:'-2px'}}/> {c.deadline}</span></div><div className="muted" style={{fontSize:12,marginTop:8}}>{c.status} · {c.source}</div></div><div style={{textAlign:'right'}}><div className="score"><Score score={c.score}/></div><div style={{fontSize:12,margin:'6px 0 10px'}}>{c.value}</div><button className="button">Review</button></div></article>)}</section>
    <aside className="card"><div className="section-head"><h3>Deadline engine</h3><CalendarClock size={18}/></div><div className="timeline"><div className="event"><strong>Today · Review 2 prepared claims</strong><span>Highest confidence, no documentation</span></div><div className="event"><strong>In 7 days · Deadline warning</strong><span>3 claims enter urgent window</span></div><div className="event"><strong>In 14 days · Filing deadline</strong><span>Privacy & Data Settlement</span></div><div className="event"><strong>In 23 days · Filing deadline</strong><span>Consumer Subscription Settlement</span></div></div><div className="notice" style={{marginTop:18}}><WalletCards size={15} style={{verticalAlign:'-3px'}}/> Payment tracking is ready for the next phase. Browser submission is intentionally disabled until the data model is proven.</div></aside></div>
    <footer className="muted" style={{fontSize:12,marginTop:20}}>MVP v0.1 · Discovery → verification → eligibility → claim queue → deadline engine · Supervised submission comes later.</footer>
  </main>
}
