name = "govchain-us"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "govchain.us/*"
zone_name = "govchain.us"

[[routes]]
pattern = "www.govchain.us/*"
zone_name = "govchain.us"

[observability]
enabled = true
