"""
agentz.workflows.handlers.medtech_traffic_boost
-------------------------------------------
Multi-platform traffic generation for the AuthiChain MedTech vertical.
Uses browser-use to post optimized narratives to LinkedIn, Reddit, and Twitter.
"""
from __future__ import annotations

import asyncio
import os

from agentz.core.modes import ExecutionContext, Mode
from agentz.core.credentials import get_or_placeholder

# The content bundle generated by the Social Multiplier
TRAFFIC_BUNDLE = {
    "linkedin": (
        "🚀 AuthiChain is officially launching the MedTech Compliance Vertical.\n\n"
        "Medical device manufacturers can now automate ISO 13485 audit trails on-chain, "
        "reducing manual compliance labor by 80%. Stop managing recalls with spreadsheets—switch "
        "to cryptographic finality.\n\n"
        "Quantify your Year 1 savings here: authichain.com/roi-calculator\n\n"
        "#MedTech #Blockchain #Compliance #ISO13485"
    ),
    "reddit": {
        "subreddit": "supplychain",
        "title": "Automating ISO 13485 compliance with blockchain provenance",
        "body": (
            "I've been working on a protocol that anchors device SKUs to Bitcoin L1 to eliminate "
            "audit overhead. Just launched a dedicated ROI calculator for medical device manufacturers "
            "to see if it actually makes sense for their scale. Would love the community's feedback "
            "on the cryptographic approach: authichain.com/roi-calculator"
        )
    },
    "twitter": (
        "1/ MedTech manufacturers: Recalls cost $200B+ annually. Manual audits are the bottleneck.\n"
        "2/ AuthiChain just launched a high-ticket vertical to automate ISO 13485 provenance on-chain.\n"
        "3/ Quantify your Year 1 savings in <2 mins using our new ROI calculator: authichain.com/roi-calculator 🚀"
    )
}

TASK_PROMPT = f"""\
Task 1: LinkedIn Post
- Navigate to https://www.linkedin.com/feed/
- Create a new post with this text:
{TRAFFIC_BUNDLE['linkedin']}
- Click Post.

Task 2: Reddit Post
- Navigate to https://www.reddit.com/r/{TRAFFIC_BUNDLE['reddit']['subreddit']}/submit
- Enter Title: {TRAFFIC_BUNDLE['reddit']['title']}
- Enter Body: {TRAFFIC_BUNDLE['reddit']['body']}
- Click Post.

Task 3: Twitter/X Post
- Navigate to https://x.com/compose/post
- Enter this text:
{TRAFFIC_BUNDLE['twitter']}
- Click Post.

Wait for user login/MFA if sessions are not already active in the browser.
"""


def run(ctx: ExecutionContext) -> str:
    # Requires session cookies for all platforms
    get_or_placeholder("linkedin_session", ctx)
    get_or_placeholder("reddit_session", ctx)
    get_or_placeholder("twitter_session", ctx)

    if ctx.mode == Mode.DRY_RUN:
        ctx.step("would open LinkedIn and post MedTech announcement")
        ctx.step("would open Reddit r/supplychain and post provenance thread")
        ctx.step("would open X.com and post ROI calculator thread")
        return "dry-run complete"

    return asyncio.run(_run_browser_task(ctx))


async def _run_browser_task(ctx: ExecutionContext) -> str:
    from browser_use import Agent
    from langchain_openai import ChatOpenAI
    
    class LLMWrapper:
        """Wrapper to add 'provider' and 'model' fields without breaking Pydantic validation."""
        def __init__(self, model, provider):
            self.llm = model
            self.provider = provider
            self.model = (
                getattr(model, "model_name", None) or 
                getattr(model, "model", None) or 
                "unknown-model"
            )
        def __getattr__(self, name):
            return getattr(self.llm, name)
        async def ainvoke(self, *args, **kwargs):
            return await self.llm.ainvoke(*args, **kwargs)
        def invoke(self, *args, **kwargs):
            return self.llm.invoke(*args, **kwargs)

    openai_key = os.environ.get("OPENAI_API_KEY")
    if not openai_key:
        raise RuntimeError("OPENAI_API_KEY required for browser-use social posting")

    raw_llm = ChatOpenAI(model="gpt-4o", api_key=openai_key)
    llm = LLMWrapper(raw_llm, "openai")

    from browser_use import Browser, BrowserConfig
    browser = Browser(config=BrowserConfig(headless=True))

    agent = Agent(
        task=TASK_PROMPT,
        llm=llm,
        browser=browser,
    )
    
    history = await agent.run(max_steps=50)
    await browser.close()
    return "Social Traffic Boost complete. Check platforms for live posts."
