name = "authichain-telegram"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_name = "authichain-telegram-db"
database_id = "3a330910-b81a-43e9-b3fb-bd8e529cff07"

[[kv_namespaces]]
binding = "SESSIONS"
id = "11d0f66da4ae4cb3890c7a75e6ecc0f5"

[vars]
ENVIRONMENT = "production"
