-- Programmatic-SEO pages generated by server/agents/seo-content.ts, gated by
-- the content.publish guardrail channel. Served dynamically alongside the
-- statically committed pages in content/seo/pages.json.
CREATE TABLE IF NOT EXISTS "seo_pages" (
  "id" serial PRIMARY KEY NOT NULL,
  "slug" varchar(80) NOT NULL UNIQUE,
  "keyword" varchar(256) NOT NULL,
  "brand" varchar(64) NOT NULL,
  "domain" varchar(128) NOT NULL,
  "title" varchar(60) NOT NULL,
  "metaDescription" varchar(155) NOT NULL,
  "h1" varchar(256) NOT NULL,
  "bodyHtml" text NOT NULL,
  "jsonLd" jsonb NOT NULL,
  "createdAt" timestamp DEFAULT now() NOT NULL
);
