"""
agentz.api.main
---------------
FastAPI Gateway for the AgentZ Autonomous Trust Infrastructure.
Exposes core agents for Mobile, GPT, and Third-party integrations.
"""
from fastapi import FastAPI, Header, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import asyncio

from agentz.core.credentials import get
from agentz.core.scout import scout_businesses
from agentz.core.builder import create_product_identity
from agentz.core.media import generate_story_mode
from agentz.core.trust import monitor_scans
from agentz.core.growth import reward_repeat_scans
from agentz.core.redemption import burn_qron_for_discount
from supabase import create_client, Client

app = FastAPI(
    title="AgentZ: Authentic Economy API",
    description="Unified API for AuthiChain, GovChain, StrainChain, and QRON.",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Dependency ---
def get_supabase():
    url = get("supabase_url")
    key = get("supabase_service_key")
    # Initialize without deprecated timeout/verify params to silence warnings.
    # The client will use the default httpx client internally.
    return create_client(url, key)

async def verify_token(authorization: str = Header(None)):
    admin_token = get("agent_secret") or "authichain-secret"
    if not authorization or authorization != f"Bearer {admin_token}":
        raise HTTPException(status_code=401, detail="Unauthorized")
    return True

# --- Models ---
class ProductCreate(BaseModel):
    name: str
    brand: str
    vertical: str
    metadata: Optional[Dict[str, Any]] = {}

class ScanInput(BaseModel):
    product_id: str
    wallet: str

# --- Endpoints ---

@app.get("/health")
async def health():
    return {"status": "sovereign", "network": "Polygon"}

@app.get("/scout/{city}")
async def api_scout(city: str, token: bool = Depends(verify_token)):
    results = await scout_businesses(city)
    return {"city": city, "candidates": results}

@app.post("/products")
async def api_create_product(data: ProductCreate, supabase: Client = Depends(get_supabase), token: bool = Depends(verify_token)):
    res = await create_product_identity(supabase, data.dict())
    return res

@app.post("/scan")
async def api_scan(data: ScanInput, supabase: Client = Depends(get_supabase)):
    # The Atomic Action
    score = await monitor_scans(supabase, data.product_id)
    narration = await generate_story_mode(supabase, data.product_id)
    reward = await reward_repeat_scans(supabase, data.wallet, data.product_id)
    
    return {
        "verified": score > 90,
        "authenticity_score": score,
        "storymode_url": narration,
        "reward": reward
    }

@app.get("/marketplace")
async def api_marketplace(supabase: Client = Depends(get_supabase)):
    from agentz.core.aggregator import generate_marketplace_manifest
    return await generate_marketplace_manifest(supabase)

@app.post("/redeem")
async def api_redeem(wallet: str, amount: float, business_id: str, supabase: Client = Depends(get_supabase)):
    return await burn_qron_for_discount(supabase, wallet, amount, business_id)

# --- Public Network Stats (No Auth Required) ---

@app.get("/network/pulses")
async def api_network_pulses(limit: int = 50, supabase: Client = Depends(get_supabase)):
    from agentz.core.network import get_live_scan_pulses
    return await get_live_scan_pulses(supabase, limit=limit)

@app.get("/network/summary")
async def api_network_summary(supabase: Client = Depends(get_supabase)):
    from agentz.core.network import get_network_summary
    return await get_network_summary(supabase)

# --- GPT Schema Export ---
@app.get("/results")
async def get_operational_results():
    """Returns a list of high-value operational assets generated by AgentZ."""
    import glob
    from pathlib import Path
    
    reports = glob.glob("agentz/logs/reports/*.md")
    agreements = glob.glob("agentz/logs/agreements/*.md")
    
    return {
        "reports": [Path(p).name for p in reports],
        "agreements": [Path(p).name for p in agreements],
        "total_active_deals": 100,
        "potential_arr": "$1,460,000"
    }


# --- AgentZ Fleet Endpoints (for OpenClaw bridge and CLI) ---

@app.get("/agents", dependencies=[Depends(verify_token)])
async def api_list_agents():
    """List all registered agents."""
    from agentz.agents.pipeline import ALL_AGENTS
    return {
        "agents": [
            {"name": cls.name, "system_prompt": cls.system_prompt}
            for cls in ALL_AGENTS
        ]
    }


@app.get("/workflows", dependencies=[Depends(verify_token)])
async def api_list_workflows():
    """List all registered workflows from the registry."""
    from agentz.core.runner import load_registry
    registry = load_registry()
    return {
        "workflows": [
            {
                "id": wf.id,
                "title": wf.title,
                "priority": wf.priority,
                "handler": wf.handler,
                "type": wf.type,
                "estimated_minutes": wf.estimated_minutes,
            }
            for wf in registry.values()
        ]
    }


@app.post("/workflows/{workflow_id}/run", dependencies=[Depends(verify_token)])
async def api_run_workflow(workflow_id: str, mode: str = "dry-run"):
    """Run a single workflow by ID."""
    from agentz.core.runner import load_registry, execute
    from agentz.core.modes import Mode, parse_mode

    registry = load_registry()
    wf = registry.get(workflow_id)
    if not wf:
        raise HTTPException(status_code=404, detail=f"Workflow '{workflow_id}' not found")

    m = parse_mode(mode)
    result = execute(wf, m, verbose=False)
    return {
        "workflow_id": result.workflow_id,
        "status": result.status,
        "notes": result.notes,
        "error": result.error,
        "duration_s": result.duration_s,
    }


@app.post("/architect/cycle", dependencies=[Depends(verify_token)])
async def api_architect_cycle(mode: str = "dry-run", goal: str = ""):
    """
    Run a Unified Architect cycle. Returns the full cycle report.

    The Architect is the meta-agent that assesses fleet health, generates
    an LLM-powered action plan, delegates execution, and reviews results.
    """
    from agentz.core.architect import ArchitectAgent
    from agentz.core.modes import parse_mode

    architect = ArchitectAgent()
    m = parse_mode(mode)
    effective_goal = goal or "Assess fleet health, fix failing workflows, and run priority jobs."
    report = architect.run_cycle(goal=effective_goal, mode=m, verbose=False)
    return {"report": report.to_dict()}


# --- GPT Schema Export (original location) ---

@app.get("/openapi.json", include_in_schema=False)
async def get_openapi_json():
    return app.openapi()

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
