name = "qron-space"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "qron.space/*"
zone_name = "qron.space"

[[routes]]
pattern = "www.qron.space/*"
zone_name = "qron.space"

[observability]
enabled = true
