/**
 * Revenue Engine — Typed event definitions.
 * All revenue-relevant events flow through these types.
 */

// ---------------------------------------------------------------------------
// Core shared fields
// ---------------------------------------------------------------------------
interface BaseEvent {
  id: string;         // uuid generated by caller
  brand: string;      // e.g. 'authichain.com' | 'strainchain.io'
  created_at: string; // ISO timestamp
}

// ---------------------------------------------------------------------------
// Verification Events
// ---------------------------------------------------------------------------
export interface VerificationEvent extends BaseEvent {
  type: 'verification';
  seal_id: string;
  scan_context: {
    ip?: string;
    user_agent?: string;
    location?: string;
    referrer?: string;
    [key: string]: unknown;
  };
  status: 'valid' | 'invalid' | 'expired';
}

// ---------------------------------------------------------------------------
// Certificate Events
// ---------------------------------------------------------------------------
export interface CertificateMintedEvent extends BaseEvent {
  type: 'certificate_minted';
  certificate_id: string;
  product_id: string;
  seal_id: string;
  rarity_score: number;
  polygon_nft_tx: string;
}

// ---------------------------------------------------------------------------
// Scan / Dispensary Events (StrainChain)
// ---------------------------------------------------------------------------
export interface ScanEvent extends BaseEvent {
  type: 'dispensary_scan';
  dispensary_id: string;
  batch_id: string;
  scan_context: {
    location?: string;
    [key: string]: unknown;
  };
}

// ---------------------------------------------------------------------------
// Subscription Events (Stripe -> Supabase)
// ---------------------------------------------------------------------------
export interface SubscriptionCreatedEvent extends BaseEvent {
  type: 'subscription_created';
  stripe_customer_id: string;
  stripe_subscription_id: string;
  plan_id: string;
  email: string;
  status: string;
  current_period_end: string;
}

export interface PaymentFailedEvent extends BaseEvent {
  type: 'payment_failed';
  stripe_customer_id: string;
  stripe_subscription_id: string;
  invoice_id: string;
  amount_due: number;
  reason?: string;
  occurred_at?: string;
}

// ---------------------------------------------------------------------------
// Union
// ---------------------------------------------------------------------------
export type RevenueEvent =
  | VerificationEvent
  | CertificateMintedEvent
  | ScanEvent
  | SubscriptionCreatedEvent
  | PaymentFailedEvent;
