name = "authichain-scan-validate"
main = "src/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = true

[vars]
NEXT_PUBLIC_SITE_URL = "https://authichain.com"

[[d1_databases]]
binding = "DB"
database_name = "authichain-db"
database_id = "ebd8081b-ac13-485a-8b0e-a6cd9c0f7be5"
migrations_dir = "migrations"
