name = "{{ID}}-vertical"
main = "src/index.ts"
compatibility_date = "2026-06-01"
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = false

[[routes]]
pattern = "{{DOMAIN}}/"
zone_name = "{{DOMAIN}}"

[[routes]]
pattern = "www.{{DOMAIN}}/"
zone_name = "{{DOMAIN}}"
