name = "authichain-license-issuer"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = true

[[d1_databases]]
binding = "DATABASE"
database_name = "authichain-license-db"
database_id = "7757b9f2-d25f-4561-866b-37392d5cb660"

[[kv_namespaces]]
binding = "SESSIONS"
id = "48d7f33917be4a7fb86c852ae0ef7033"

[vars]
ENVIRONMENT = "production"
