#!/usr/bin/env bash
# Regenerates docs/superpowers/plans/worker-inventory.md from the workers/
# tree — the durable answer to the fleet doc going stale (the hand-written
# worker-status-2026-04-27.md drifted within weeks). Run any time; CI runs it
# monthly (repo-maintenance.yml) and fails if the committed doc is out of date.

set -eo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${REPO_ROOT}/docs/superpowers/plans/worker-inventory.md"

{
  echo "# Cloudflare Worker Inventory (generated)"
  echo
  echo "_Generated by \`scripts/gen-worker-inventory.sh\`. Do not edit by hand —"
  echo "regenerate after adding/renaming workers. CI checks this monthly._"
  echo
  echo "| Dir | Worker name | Main | Routes | Crons |"
  echo "|---|---|---|---|---|"

  for dir in "${REPO_ROOT}"/workers/*/ "${REPO_ROOT}"/worker/; do
    toml="${dir}wrangler.toml"
    [ -f "$toml" ] || continue
    rel="${dir#"${REPO_ROOT}"/}"
    name="$(grep -E '^name *= *' "$toml" | head -1 | sed -E 's/^name *= *"?([^"]*)"?/\1/' || true)"
    main="$(grep -E '^main *= *' "$toml" | head -1 | sed -E 's/^main *= *"?([^"]*)"?/\1/' || true)"
    routes="$({ grep -E '^ *pattern *= *' "$toml" || true; } | sed -E 's/^ *pattern *= *"?([^",]*)"?,?/\1/' | paste -sd ', ' -)"
    crons="$({ grep -E '^ *crons *= *' "$toml" || true; } | head -1 | sed -E 's/^ *crons *= *//')"
    echo "| ${rel%/} | ${name:--} | ${main:--} | ${routes:--} | ${crons:--} |"
  done

  echo
  echo "Root app worker: \`wrangler.app.jsonc\` (authichain-app, OpenNext build)."
  echo "Deploy paths: \`.github/workflows/deploy-workers.yml\` (workers/*),"
  echo "\`deploy-cloudflare.yml\`, \`deploy-edge-worker.yml\` (api/),"
  echo "\`deploy-app-worker.yml\` (app)."
} > "$OUT"

echo "Wrote ${OUT#"${REPO_ROOT}"/}"
