-- Superseded migration filename. The applied production migration was recorded as
-- 20261001000121_musa_supplier_evidence_registry because Supabase assigned the
-- migration version at application time. The canonical repository migration is
-- tracked under that applied version; this placeholder prevents accidental replay.
