name = "authichain-automation"
main = "index.js"
compatibility_date = "2024-09-23"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "authichain-db"
database_id = "ebd8081b-ac13-485a-8b0e-a6cd9c0f7be5"

[durable_objects]
bindings = [
  { name = "RATE_LIMITER", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]
