name = "bitcoin-auth"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "bitcoin-auth.authichain.com/*"
zone_name = "authichain.com"

[vars]
BITCOIN_NETWORK = "mainnet"

[observability]
enabled = true
