name = "bitcoin-auth"
main = "src/index.ts"
compatibility_date = "2026-04-01"
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = false

[[routes]]
pattern = "bitcoin-auth.authichain.com/*"
zone_name = "authichain.com"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "AUTH_KV_ID_REPLACE_ME"

[vars]
BITCOIN_NETWORK = "mainnet"
