name = "authichain-infra"
main = "src/index.ts"
compatibility_date = "2026-04-01"
account_id = "4c1869b90f13f86940aa3747839bf420"
workers_dev = false

[triggers]
crons = ["0 */6 * * *"]

[vars]
ALERT_EMAIL = "authichain@gmail.com"
RESEND_RELAY = "https://resend-relay.undone-k.workers.dev/emails"

[[kv_namespaces]]
binding = "INFRA_KV"
id = "0dbdce2318f14984b0a9c56bf2db83e7"
