name: Node + pnpm Setup

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      pnpm_version:
        required: true
        type: string
    secrets:
      SUPABASE_URL:
        required: false
      SUPABASE_SERVICE_ROLE_KEY:
        required: false

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86
        with:
          version: ${{ inputs.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile --config.minimumReleaseAge=0
